name: delivery Action

on:
  push:
    branches:
      - main

jobs:
  My-deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: project
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          envs: APPLICATION_PROPERTIES
        run: echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
